services:
  - type: web
    name: moveMentor
    env: node
    plan: free
    buildCommand: cd front && npm install && npm run build && cd ..
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: front/build
    routes:
      - type: rewrite
        source: /
        destination: /index.html
